server {
    listen 4000;
    listen [::]:4000;

    server_name _; # Menangkap semua host/IP, aman karena ditunnel

    # Lokasi hasil build Vite (folder dist)
    root /var/www/temanbeli/react/dist;
    index index.html;

    location / {
        # Agar React Router jalan dan tidak 404 saat navigasi/refresh
        try_files $uri $uri/ /index.html;
    }

    # Optimasi cache untuk asset statis (opsional)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
        expires max;
        log_not_found off;
    }
}
